In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
KF = pd.read_csv("train.csv")
KF

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [3]:
print(f"Number of Rows: {KF.shape[0]}\nNumber of Columns: {KF.shape[1]}")

Number of Rows: 8693
Number of Columns: 14

In [4]:
KF.head(2)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True

In [5]:
KF.tail(2)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [6]:
KF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [7]:
KF.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

In [8]:
for i in KF.columns:
    print(i)

PassengerId
HomePlanet
CryoSleep
Cabin
Destination
Age
VIP
RoomService
FoodCourt
ShoppingMall
Spa
VRDeck
Name
Transported

In [9]:
KF.count()

PassengerId     8693
HomePlanet      8492
CryoSleep       8476
Cabin           8494
Destination     8511
Age             8514
VIP             8490
RoomService     8512
FoodCourt       8510
ShoppingMall    8485
Spa             8510
VRDeck          8505
Name            8493
Transported     8693
dtype: int64

In [10]:
KF.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [11]:
def fillNaMean(KF, categorical_cols):
    for col in categorical_cols:
        KF[col] = KF[col].fillna(KF[col].mode()[0])
categorical_columns = [
    'HomePlanet','CryoSleep','Cabin','Destination',
    'Age','VIP','RoomService','FoodCourt',
    'ShoppingMall','Spa','VRDeck','Name'
]

In [12]:
KF.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [13]:
KF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [14]:
def changeFloatToInt64(cols):
    for i in cols:
        KF[i] = KF[i].replace([np.inf, -np.inf], np.nan)

        KF[i] = KF[i].fillna(0)

        KF[i] = KF[i].astype('int64')

columns = ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
changeFloatToInt64(columns)

In [15]:
KF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8693 non-null   int64
 6   VIP           8490 non-null   object
 7   RoomService   8693 non-null   int64
 8   FoodCourt     8693 non-null   int64
 9   ShoppingMall  8693 non-null   int64
 10  Spa           8693 non-null   int64
 11  VRDeck        8693 non-null   int64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), int64(6), object(7)
memory usage: 891.5+ KB

In [18]:
def encodeCols(cols):
    for i in cols:
        temp = pd.DataFrame({i:KF[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(temp))
        KF[i] = data_LE.transform(KF[i])

columns = ['PassengerId','HomePlanet','Cabin','Destination','Name','CryoSleep','VIP']
encodeCols(columns)

In [19]:
KF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   int64
 1   HomePlanet    8693 non-null   int64
 2   CryoSleep     8693 non-null   int32
 3   Cabin         8693 non-null   int64
 4   Destination   8693 non-null   int32
 5   Age           8693 non-null   int64
 6   VIP           8693 non-null   int32
 7   RoomService   8693 non-null   int64
 8   FoodCourt     8693 non-null   int64
 9   ShoppingMall  8693 non-null   int64
 10  Spa           8693 non-null   int64
 11  VRDeck        8693 non-null   int64
 12  Name          8693 non-null   int32
 13  Transported   8693 non-null   bool
dtypes: bool(1), int32(4), int64(9)
memory usage: 755.7 KB

In [20]:
KF.drop('PassengerId', axis=1, inplace=True)
KF.drop('Name', axis=1, inplace=True)
KF.drop('RoomService', axis=1, inplace=True)

In [21]:
KF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8693 non-null   int64
 1   CryoSleep     8693 non-null   int32
 2   Cabin         8693 non-null   int64
 3   Destination   8693 non-null   int32
 4   Age           8693 non-null   int64
 5   VIP           8693 non-null   int32
 6   FoodCourt     8693 non-null   int64
 7   ShoppingMall  8693 non-null   int64
 8   Spa           8693 non-null   int64
 9   VRDeck        8693 non-null   int64
 10  Transported   8693 non-null   bool
dtypes: bool(1), int32(3), int64(7)
memory usage: 585.9 KB

In [22]:
KF['Transported'] = KF['Transported'].astype(int)

In [23]:
X = KF.drop(columns=['Transported'])
y = KF['Transported']

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
model = RandomForestClassifier()
model.fit(X, y)

RandomForestClassifier()

In [27]:
K = pd.read_csv("test.csv")
K

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [28]:
K.drop('PassengerId', axis=1, inplace=True)
K.drop('Name', axis=1, inplace=True)
K.drop('RoomService', axis=1, inplace=True)

In [29]:
K.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    4190 non-null   object
 1   CryoSleep     4184 non-null   object
 2   Cabin         4177 non-null   object
 3   Destination   4185 non-null   object
 4   Age           4186 non-null   float64
 5   VIP           4184 non-null   object
 6   FoodCourt     4171 non-null   float64
 7   ShoppingMall  4179 non-null   float64
 8   Spa           4176 non-null   float64
 9   VRDeck        4197 non-null   float64
dtypes: float64(5), object(5)
memory usage: 334.3+ KB

In [30]:
def encodeCols(cols):
    for i in cols:
        temp = pd.DataFrame({i:K[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(temp))
        K[i] = data_LE.transform(K[i])

columns = ['HomePlanet','CryoSleep','Cabin','Destination','VIP',]
encodeCols(columns)

In [31]:
K.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    4277 non-null   int32
 1   CryoSleep     4277 non-null   int32
 2   Cabin         4277 non-null   int32
 3   Destination   4277 non-null   int32
 4   Age           4186 non-null   float64
 5   VIP           4277 non-null   int32
 6   FoodCourt     4171 non-null   float64
 7   ShoppingMall  4179 non-null   float64
 8   Spa           4176 non-null   float64
 9   VRDeck        4197 non-null   float64
dtypes: float64(5), int32(5)
memory usage: 250.7 KB

In [33]:
def fillNaMean(K, categorical_cols):
    for col in categorical_cols:
        K[col] = K[col].fillna(K[col].mode()[0])

categorical_columns = ['Age','FoodCourt','ShoppingMall','Spa','VRDeck']

fillNaMean(K, categorical_columns)

In [34]:
K.isnull().sum()

HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64

In [35]:
K.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    4277 non-null   int32
 1   CryoSleep     4277 non-null   int32
 2   Cabin         4277 non-null   int32
 3   Destination   4277 non-null   int32
 4   Age           4277 non-null   float64
 5   VIP           4277 non-null   int32
 6   FoodCourt     4277 non-null   float64
 7   ShoppingMall  4277 non-null   float64
 8   Spa           4277 non-null   float64
 9   VRDeck        4277 non-null   float64
dtypes: float64(5), int32(5)
memory usage: 250.7 KB

In [36]:
def changeFloatToInK64(cols):
    for i in cols:
        K[i] = K[i].astype('int64')

columns = ['VRDeck', 'Spa','ShoppingMall', 'FoodCourt','Age']
changeFloatToInK64(columns)

In [38]:
K.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    4277 non-null   int32
 1   CryoSleep     4277 non-null   int32
 2   Cabin         4277 non-null   int32
 3   Destination   4277 non-null   int32
 4   Age           4277 non-null   int64
 5   VIP           4277 non-null   int32
 6   FoodCourt     4277 non-null   int64
 7   ShoppingMall  4277 non-null   int64
 8   Spa           4277 non-null   int64
 9   VRDeck        4277 non-null   int64
dtypes: int32(5), int64(5)
memory usage: 250.7 KB

In [39]:
Predict = model.predict(K)
Predict

array([1, 0, 1, ..., 1, 1, 1])

In [40]:
bool = (Predict >= 0.5).astype(bool)
bool

array([ True, False,  True, ...,  True,  True,  True])

In [41]:
submission = pd.read_csv("sample_submission.csv")
submission['Transported'] = bool
submission.to_csv("sample_submission.csv", index=False)