In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
print(f"Number of Rows: {df.shape[0]}\nNumber of Columns: {df.shape[1]}")

Number of Rows: 891
Number of Columns: 12

In [4]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
for k in df.columns:
    print(k)

PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked

In [9]:
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [10]:
df['Survived'].unique()

array([0, 1], dtype=int64)

In [11]:
df['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [12]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [13]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [15]:
def fillNaMean(df, categorical_cols):
    for col in categorical_cols:
        df[col] = df[col].fillna(df[col].mode()[0])

In [16]:
categorical_columns = ['Age','Cabin','Embarked']
fillNaMean(df, categorical_columns)

In [17]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [19]:
def changeFloattoInt64(cols):
    for i in cols:
        df[i] = df[i].astype('int64')

columns = ['Age', 'Fare']
changeFloattoInt64(columns)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    int64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    int64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: int64(7), object(5)
memory usage: 83.7+ KB

In [21]:
df_clean = df.copy()

In [22]:
def encodeCols(cols):
    for i in cols:
        temp = pd.DataFrame({i:df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(temp))
        df_clean[i] = data_LE.transform(df[i])

columns = ['Sex','Ticket','Ticket','Cabin','Embarked']
encodeCols(columns)

In [23]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    int32
 5   Age          891 non-null    int64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    int32
 9   Fare         891 non-null    int64
 10  Cabin        891 non-null    int32
 11  Embarked     891 non-null    int32
dtypes: int32(4), int64(7), object(1)
memory usage: 69.7+ KB

In [24]:
df_clean.drop('Name', axis=1, inplace=True)
df_clean.drop('PassengerId', axis=1, inplace=True)

In [25]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int32
 3   Age       891 non-null    int64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Ticket    891 non-null    int32
 7   Fare      891 non-null    int64
 8   Cabin     891 non-null    int32
 9   Embarked  891 non-null    int32
dtypes: int32(4), int64(6)
memory usage: 55.8 KB

In [26]:
df_clean.to_csv(r'cleaned-data.csv', index=False, header=True)

In [27]:
df_clean.head(2)

   Survived  Pclass  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
0         0       3    1   22      1      0     523     7     47         2
1         1       1    0   38      1      0     596    71     81         0

In [28]:
X = df_clean.drop(columns=['Survived'])
y = df_clean['Survived']

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

numeric_features = ['Age', 'Fare']
categorical_features = ['Sex', 'Embarked', 'Pclass']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

model = Pipeline(steps=[('preprocessor', preprocessor),
                        ('classifier', RandomForestClassifier(n_estimators=500, random_state=42))])

model.fit(X, y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked',
                                                   'Pclass'])])),
                ('classifier',
                 RandomForestClassifier(n_estimators=500, random_state=42))])

In [30]:
df2 = pd.read_csv("test.csv")
df2

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [31]:
print(f"Number of Rows: {df2.shape[0]}\nNumber of Columns: {df2.shape[1]}")

Number of Rows: 418
Number of Columns: 11

In [32]:
df2.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [33]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [34]:
df2.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [35]:
for k in df2.columns:
    print(k)

PassengerId
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked

In [36]:
df2.count()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            332
SibSp          418
Parch          418
Ticket         418
Fare           417
Cabin           91
Embarked       418
dtype: int64

In [37]:
df2['Name'].unique()

array(['Kelly, Mr. James', 'Wilkes, Mrs. James (Ellen Needs)',
       'Myles, Mr. Thomas Francis', 'Wirz, Mr. Albert',
       'Hirvonen, Mrs. Alexander (Helga E Lindqvist)',
       'Svensson, Mr. Johan Cervin', 'Connolly, Miss. Kate',
       'Caldwell, Mr. Albert Francis',
       'Abrahim, Mrs. Joseph (Sophie Halaut Easu)',
       'Davies, Mr. John Samuel', 'Ilieff, Mr. Ylio',
       'Jones, Mr. Charles Cresson',
       'Snyder, Mrs. John Pillsbury (Nelle Stevenson)',
       'Howard, Mr. Benjamin',
       'Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)',
       'del Carlo, Mrs. Sebastiano (Argenia Genovesi)',
       'Keane, Mr. Daniel', 'Assaf, Mr. Gerios',
       'Ilmakangas, Miss. Ida Livija',
       'Assaf Khalil, Mrs. Mariana (Miriam")"', 'Rothschild, Mr. Martin',
       'Olsen, Master. Artur Karl',
       'Flegenheim, Mrs. Alfred (Antoinette)',
       'Williams, Mr. Richard Norris II',
       'Ryerson, Mrs. Arthur Larned (Emily Maria Borie)',
       'Robins, Mr. Alexander A', 'Ostby, Miss. Helene Ragnhild',
       'Daher, Mr. Shedid', 'Brady, Mr. John Bertram',
       'Samaan, Mr. Elias', 'Louch, Mr. Charles Alexander',
       'Jefferys, Mr. Clifford Thomas',
       'Dean, Mrs. Bertram (Eva Georgetta Light)',
       'Johnston, Mrs. Andrew G (Elizabeth Lily" Watson)"',
       'Mock, Mr. Philipp Edmund',
       'Katavelas, Mr. Vassilios (Catavelas Vassilios")"',
       'Roth, Miss. Sarah A', 'Cacic, Miss. Manda', 'Sap, Mr. Julius',
       'Hee, Mr. Ling', 'Karun, Mr. Franz', 'Franklin, Mr. Thomas Parham',
       'Goldsmith, Mr. Nathan', 'Corbett, Mrs. Walter H (Irene Colvin)',
       'Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)',
       'Peltomaki, Mr. Nikolai Johannes', 'Chevre, Mr. Paul Romaine',
       'Shaughnessy, Mr. Patrick',
       'Bucknell, Mrs. William Robert (Emma Eliza Ward)',
       'Coutts, Mrs. William (Winnie Minnie" Treanor)"',
       'Smith, Mr. Lucien Philip', 'Pulbaum, Mr. Franz',
       'Hocking, Miss. Ellen Nellie""', 'Fortune, Miss. Ethel Flora',
       'Mangiavacchi, Mr. Serafino Emilio', 'Rice, Master. Albert',
       'Cor, Mr. Bartol', 'Abelseth, Mr. Olaus Jorgensen',
       'Davison, Mr. Thomas Henry', 'Chaudanson, Miss. Victorine',
       'Dika, Mr. Mirko', 'McCrae, Mr. Arthur Gordon',
       'Bjorklund, Mr. Ernst Herbert', 'Bradley, Miss. Bridget Delia',
       'Ryerson, Master. John Borie',
       'Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)',
       'Burns, Miss. Mary Delia', 'Moore, Mr. Clarence Bloomfield',
       'Tucker, Mr. Gilbert Milligan Jr',
       'Fortune, Mrs. Mark (Mary McDougald)', 'Mulvihill, Miss. Bertha E',
       'Minkoff, Mr. Lazar', 'Nieminen, Miss. Manta Josefina',
       'Ovies y Rodriguez, Mr. Servando', 'Geiger, Miss. Amalie',
       'Keeping, Mr. Edwin', 'Miles, Mr. Frank',
       'Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)',
       'Aldworth, Mr. Charles Augustus', 'Doyle, Miss. Elizabeth',
       'Boulos, Master. Akar', 'Straus, Mr. Isidor',
       'Case, Mr. Howard Brown', 'Demetri, Mr. Marinko',
       'Lamb, Mr. John Joseph', 'Khalil, Mr. Betros',
       'Barry, Miss. Julia', 'Badman, Miss. Emily Louisa',
       "O'Donoghue, Ms. Bridget", 'Wells, Master. Ralph Lester',
       'Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)',
       'Pedersen, Mr. Olaf', 'Davidson, Mrs. Thornton (Orian Hays)',
       'Guest, Mr. Robert', 'Birnbaum, Mr. Jakob',
       'Tenglin, Mr. Gunnar Isidor',
       'Cavendish, Mrs. Tyrell William (Julia Florence Siegel)',
       'Makinen, Mr. Kalle Edvard', 'Braf, Miss. Elin Ester Maria',
       'Nancarrow, Mr. William Henry',
       'Stengel, Mrs. Charles Emil Henry (Annie May Morris)',
       'Weisz, Mr. Leopold', 'Foley, Mr. William',
       'Johansson Palmquist, Mr. Oskar Leander',
       'Thomas, Mrs. Alexander (Thamine Thelma")"',
       'Holthen, Mr. Johan Martin', 'Buckley, Mr. Daniel',
       'Ryan, Mr. Edward', 'Willer, Mr. Aaron (Abi Weller")"',
       'Swane, Mr. George', 'Stanton, Mr. Samuel Ward',
       'Shine, Miss. Ellen Natalia', 'Evans, Miss. Edith Corse',
       'Buckley, Miss. Katherine',
       'Straus, Mrs. Isidor (Rosalie Ida Blun)',
       'Chronopoulos, Mr. Demetrios', 'Thomas, Mr. John',
       'Sandstrom, Miss. Beatrice Irene', 'Beattie, Mr. Thomson',
       'Chapman, Mrs. John Henry (Sara Elizabeth Lawry)',
       'Watt, Miss. Bertha J', 'Kiernan, Mr. John',
       'Schabert, Mrs. Paul (Emma Mock)', 'Carver, Mr. Alfred John',
       'Kennedy, Mr. John', 'Cribb, Miss. Laura Alice',
       'Brobeck, Mr. Karl Rudolf', 'McCoy, Miss. Alicia',
       'Bowenur, Mr. Solomon', 'Petersen, Mr. Marius',
       'Spinner, Mr. Henry John', 'Gracie, Col. Archibald IV',
       'Lefebre, Mrs. Frank (Frances)', 'Thomas, Mr. Charles P',
       'Dintcheff, Mr. Valtcho', 'Carlsson, Mr. Carl Robert',
       'Zakarian, Mr. Mapriededer', 'Schmidt, Mr. August',
       'Drapkin, Miss. Jennie', 'Goodwin, Mr. Charles Frederick',
       'Goodwin, Miss. Jessie Allis', 'Daniels, Miss. Sarah',
       'Ryerson, Mr. Arthur Larned', 'Beauchamp, Mr. Henry James',
       'Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey")"',
       'Vander Planke, Mr. Julius', 'Hilliard, Mr. Herbert Henry',
       'Davies, Mr. Evan', 'Crafton, Mr. John Bertram',
       'Lahtinen, Rev. William', 'Earnshaw, Mrs. Boulton (Olive Potter)',
       'Matinoff, Mr. Nicola', 'Storey, Mr. Thomas',
       'Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)',
       'Asplund, Master. Filip Oscar', 'Duquemin, Mr. Joseph',
       'Bird, Miss. Ellen', 'Lundin, Miss. Olga Elida',
       'Borebank, Mr. John James', 'Peacock, Mrs. Benjamin (Edith Nile)',
       'Smyth, Miss. Julia', 'Touma, Master. Georges Youssef',
       'Wright, Miss. Marion', 'Pearce, Mr. Ernest',
       'Peruschitz, Rev. Joseph Maria',
       'Kink-Heilmann, Mrs. Anton (Luise Heilmann)', 'Brandeis, Mr. Emil',
       'Ford, Mr. Edward Watson',
       'Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)',
       'Hellstrom, Miss. Hilda Maria', 'Lithman, Mr. Simon',
       'Zakarian, Mr. Ortin', 'Dyker, Mr. Adolf Fredrik',
       'Torfa, Mr. Assad', 'Asplund, Mr. Carl Oscar Vilhelm Gustafsson',
       'Brown, Miss. Edith Eileen', 'Sincock, Miss. Maude',
       'Stengel, Mr. Charles Emil Henry',
       'Becker, Mrs. Allen Oliver (Nellie E Baumgardner)',
       'Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)',
       'McCrie, Mr. James Matthew', 'Compton, Mr. Alexander Taylor Jr',
       'Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)',
       'Lane, Mr. Patrick',
       'Douglas, Mrs. Frederick Charles (Mary Helene Baxter)',
       'Maybery, Mr. Frank Hubert',
       'Phillips, Miss. Alice Frances Louisa', 'Davies, Mr. Joseph',
       'Sage, Miss. Ada', 'Veal, Mr. James', 'Angle, Mr. William A',
       'Salomon, Mr. Abraham L', 'van Billiard, Master. Walter John',
       'Lingane, Mr. John', 'Drew, Master. Marshall Brines',
       'Karlsson, Mr. Julius Konrad Eugen',
       'Spedden, Master. Robert Douglas', 'Nilsson, Miss. Berta Olivia',
       'Baimbrigge, Mr. Charles Robert',
       'Rasmussen, Mrs. (Lena Jacobsen Solvang)', 'Murphy, Miss. Nora',
       'Danbom, Master. Gilbert Sigvard Emanuel',
       'Astor, Col. John Jacob', 'Quick, Miss. Winifred Vera',
       'Andrew, Mr. Frank Thomas', 'Omont, Mr. Alfred Fernand',
       'McGowan, Miss. Katherine', 'Collett, Mr. Sidney C Stuart',
       'Rosenbaum, Miss. Edith Louise', 'Delalic, Mr. Redjo',
       'Andersen, Mr. Albert Karvin', 'Finoli, Mr. Luigi',
       'Deacon, Mr. Percy William',
       'Howard, Mrs. Benjamin (Ellen Truelove Arman)',
       'Andersson, Miss. Ida Augusta Margareta', 'Head, Mr. Christopher',
       'Mahon, Miss. Bridget Delia', 'Wick, Mr. George Dennick',
       'Widener, Mrs. George Dunton (Eleanor Elkins)',
       'Thomson, Mr. Alexander Morrison',
       'Duran y More, Miss. Florentina', 'Reynolds, Mr. Harold J',
       'Cook, Mrs. (Selena Rogers)', 'Karlsson, Mr. Einar Gervasius',
       'Candee, Mrs. Edward (Helen Churchill Hungerford)',
       'Moubarek, Mrs. George (Omine Amenia" Alexander)"',
       'Asplund, Mr. Johan Charles', 'McNeill, Miss. Bridget',
       'Everett, Mr. Thomas James', 'Hocking, Mr. Samuel James Metcalfe',
       'Sweet, Mr. George Frederick', 'Willard, Miss. Constance',
       'Wiklund, Mr. Karl Johan', 'Linehan, Mr. Michael',
       'Cumings, Mr. John Bradley', 'Vendel, Mr. Olof Edvin',
       'Warren, Mr. Frank Manley', 'Baccos, Mr. Raffull',
       'Hiltunen, Miss. Marta',
       'Douglas, Mrs. Walter Donald (Mahala Dutton)',
       'Lindstrom, Mrs. Carl Johan (Sigrid Posse)',
       'Christy, Mrs. (Alice Frances)', 'Spedden, Mr. Frederic Oakley',
       'Hyman, Mr. Abraham', 'Johnston, Master. William Arthur Willie""',
       'Kenyon, Mr. Frederick R', 'Karnes, Mrs. J Frank (Claire Bennett)',
       'Drew, Mr. James Vivian',
       'Hold, Mrs. Stephen (Annie Margaret Hill)',
       'Khalil, Mrs. Betros (Zahie Maria" Elias)"',
       'West, Miss. Barbara J',
       'Abrahamsson, Mr. Abraham August Johannes',
       'Clark, Mr. Walter Miller', 'Salander, Mr. Karl Johan',
       'Wenzel, Mr. Linhart', 'MacKay, Mr. George William',
       'Mahon, Mr. John', 'Niklasson, Mr. Samuel',
       'Bentham, Miss. Lilian W', 'Midtsjo, Mr. Karl Albert',
       'de Messemaeker, Mr. Guillaume Joseph',
       'Nilsson, Mr. August Ferdinand',
       'Wells, Mrs. Arthur Henry (Addie" Dart Trevaskis)"',
       'Klasen, Miss. Gertrud Emilia',
       'Portaluppi, Mr. Emilio Ilario Giuseppe', 'Lyntakoff, Mr. Stanko',
       'Chisholm, Mr. Roderick Robert Crispin',
       'Warren, Mr. Charles William', 'Howard, Miss. May Elizabeth',
       'Pokrnic, Mr. Mate', 'McCaffry, Mr. Thomas Francis',
       'Fox, Mr. Patrick',
       'Clark, Mrs. Walter Miller (Virginia McDowell)',
       'Lennon, Miss. Mary', 'Saade, Mr. Jean Nassr',
       'Bryhl, Miss. Dagmar Jenny Ingeborg ',
       'Parker, Mr. Clifford Richard', 'Faunthorpe, Mr. Harry',
       'Ware, Mr. John James', 'Oxenham, Mr. Percy Thomas',
       'Oreskovic, Miss. Jelka', 'Peacock, Master. Alfred Edward',
       'Fleming, Miss. Honora', 'Touma, Miss. Maria Youssef',
       'Rosblom, Miss. Salli Helena', 'Dennis, Mr. William',
       'Franklin, Mr. Charles (Charles Fardon)',
       'Snyder, Mr. John Pillsbury', 'Mardirosian, Mr. Sarkis',
       'Ford, Mr. Arthur', 'Rheims, Mr. George Alexander Lucien',
       'Daly, Miss. Margaret Marcella Maggie""', 'Nasr, Mr. Mustafa',
       'Dodge, Dr. Washington', 'Wittevrongel, Mr. Camille',
       'Angheloff, Mr. Minko', 'Laroche, Miss. Louise',
       'Samaan, Mr. Hanna', 'Loring, Mr. Joseph Holland',
       'Johansson, Mr. Nils', 'Olsson, Mr. Oscar Wilhelm',
       'Malachard, Mr. Noel', 'Phillips, Mr. Escott Robert',
       'Pokrnic, Mr. Tome', 'McCarthy, Miss. Catherine Katie""',
       'Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)',
       'Allison, Mr. Hudson Joshua Creighton',
       'Aks, Master. Philip Frank', 'Hays, Mr. Charles Melville',
       'Hansen, Mrs. Claus Peter (Jennie L Howard)',
       'Cacic, Mr. Jego Grga', 'Vartanian, Mr. David',
       'Sadowitz, Mr. Harry', 'Carr, Miss. Jeannie',
       'White, Mrs. John Stuart (Ella Holmes)', 'Hagardon, Miss. Kate',
       'Spencer, Mr. William Augustus', 'Rogers, Mr. Reginald Harry',
       'Jonsson, Mr. Nils Hilding', 'Jefferys, Mr. Ernest Wilfred',
       'Andersson, Mr. Johan Samuel', 'Krekorian, Mr. Neshan',
       'Nesson, Mr. Israel', 'Rowe, Mr. Alfred G',
       'Kreuchen, Miss. Emilie', 'Assam, Mr. Ali',
       'Becker, Miss. Ruth Elizabeth',
       'Rosenshine, Mr. George (Mr George Thorne")"',
       'Clarke, Mr. Charles Valentine', 'Enander, Mr. Ingvar',
       'Davies, Mrs. John Morgan (Elizabeth Agnes Mary White) ',
       'Dulles, Mr. William Crothers', 'Thomas, Mr. Tannous',
       'Nakid, Mrs. Said (Waika Mary" Mowad)"', 'Cor, Mr. Ivan',
       'Maguire, Mr. John Edward', 'de Brito, Mr. Jose Joaquim',
       'Elias, Mr. Joseph', 'Denbury, Mr. Herbert',
       'Betros, Master. Seman', 'Fillbrook, Mr. Joseph Charles',
       'Lundstrom, Mr. Thure Edvin', 'Sage, Mr. John George',
       'Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)',
       'van Billiard, Master. James William',
       'Abelseth, Miss. Karen Marie', 'Botsford, Mr. William Hull',
       'Whabee, Mrs. George Joseph (Shawneene Abi-Saab)',
       'Giles, Mr. Ralph', 'Walcroft, Miss. Nellie',
       'Greenfield, Mrs. Leo David (Blanche Strouse)',
       'Stokes, Mr. Philip Joseph', 'Dibden, Mr. William',
       'Herman, Mr. Samuel', 'Dean, Miss. Elizabeth Gladys Millvina""',
       'Julian, Mr. Henry Forbes',
       'Brown, Mrs. John Murray (Caroline Lane Lamson)',
       'Lockyer, Mr. Edward', "O'Keefe, Mr. Patrick",
       'Lindell, Mrs. Edvard Bengtsson (Elin Gerda Persson)',
       'Sage, Master. William Henry',
       'Mallet, Mrs. Albert (Antoinette Magnin)',
       'Ware, Mrs. John James (Florence Louise Long)',
       'Strilic, Mr. Ivan',
       'Harder, Mrs. George Achilles (Dorothy Annan)',
       'Sage, Mrs. John (Annie Bullen)', 'Caram, Mr. Joseph',
       'Riihivouri, Miss. Susanna Juhantytar Sanni""',
       'Gibson, Mrs. Leonard (Pauline C Boeson)',
       'Pallas y Castello, Mr. Emilio', 'Giles, Mr. Edgar',
       'Wilson, Miss. Helen Alice', 'Ismay, Mr. Joseph Bruce',
       'Harbeck, Mr. William H', 'Dodge, Mrs. Washington (Ruth Vidaver)',
       'Bowen, Miss. Grace Scott', 'Kink, Miss. Maria',
       'Cotterill, Mr. Henry Harry""', 'Hipkins, Mr. William Edward',
       'Asplund, Master. Carl Edgar', "O'Connor, Mr. Patrick",
       'Foley, Mr. Joseph', 'Risien, Mrs. Samuel (Emma)',
       "McNamee, Mrs. Neal (Eileen O'Leary)",
       'Wheeler, Mr. Edwin Frederick""', 'Herman, Miss. Kate',
       'Aronsson, Mr. Ernst Axel Algot', 'Ashby, Mr. John',
       'Canavan, Mr. Patrick', 'Palsson, Master. Paul Folke',
       'Payne, Mr. Vivian Ponsonby',
       'Lines, Mrs. Ernest H (Elizabeth Lindsey James)',
       'Abbott, Master. Eugene Joseph', 'Gilbert, Mr. William',
       'Kink-Heilmann, Mr. Anton',
       'Smith, Mrs. Lucien Philip (Mary Eloise Hughes)',
       'Colbert, Mr. Patrick',
       'Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)',
       'Larsson-Rondberg, Mr. Edvard A', 'Conlon, Mr. Thomas Henry',
       'Bonnell, Miss. Caroline', 'Gale, Mr. Harry',
       'Gibson, Miss. Dorothy Winifred', 'Carrau, Mr. Jose Pedro',
       'Frauenthal, Mr. Isaac Gerald',
       'Nourney, Mr. Alfred (Baron von Drachstedt")"',
       'Ware, Mr. William Jeffery', 'Widener, Mr. George Dunton',
       'Riordan, Miss. Johanna Hannah""', 'Peacock, Miss. Treasteall',
       'Naughton, Miss. Hannah',
       'Minahan, Mrs. William Edward (Lillian E Thorpe)',
       'Henriksson, Miss. Jenny Lovisa', 'Spector, Mr. Woolf',
       'Oliva y Ocana, Dona. Fermina', 'Saether, Mr. Simon Sivertsen',
       'Ware, Mr. Frederick', 'Peter, Master. Michael J'], dtype=object)

In [38]:
df2.nunique()

PassengerId    418
Pclass           3
Name           418
Sex              2
Age             79
SibSp            7
Parch            8
Ticket         363
Fare           169
Cabin           76
Embarked         3
dtype: int64

In [39]:
df2.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [40]:
def fillNaMean(df2, categorical_cols):
    for col in categorical_cols:
        df2[col] = df2[col].fillna(df[col].mode()[0])

categorical_columns = ['Age','Cabin','Fare']
fillNaMean(df2, categorical_columns)

In [41]:
df2.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [42]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         418 non-null    float64
 9   Cabin        418 non-null    object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [43]:
def changeFloattoInt64(cols):
    for i in cols:
        df2[i] = df2[i].astype('int64')

columns = ['Age', 'Fare']
changeFloattoInt64(columns)

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          418 non-null    int64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         418 non-null    int64
 9   Cabin        418 non-null    object
 10  Embarked     418 non-null    object
dtypes: int64(6), object(5)
memory usage: 36.1+ KB

In [45]:
df2.drop('Name', axis=1, inplace=True)
df2.drop('PassengerId', axis=1, inplace=True)

In [46]:
from sklearn.preprocessing import OrdinalEncoder

def encodeCols(cols):
    ordinal = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    df2[cols] = ordinal.fit_transform(df2[cols])

columns = ['Embarked', 'Cabin', 'Ticket','Sex']
encodeCols(columns)

In [47]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    float64
 2   Age       418 non-null    int64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Ticket    418 non-null    float64
 6   Fare      418 non-null    int64
 7   Cabin     418 non-null    float64
 8   Embarked  418 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 29.5 KB

In [48]:
def changeFloattoInt64(cols):
    for i in cols:
        df2[i] = df2[i].astype('int64')

columns = ['Sex', 'Ticket','Cabin', 'Cabin', 'Embarked']
changeFloattoInt64(columns)

In [49]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    int64
 2   Age       418 non-null    int64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Ticket    418 non-null    int64
 6   Fare      418 non-null    int64
 7   Cabin     418 non-null    int64
 8   Embarked  418 non-null    int64
dtypes: int64(9)
memory usage: 29.5 KB

In [50]:
y_pred = model.predict(df2)

In [51]:
y_pred

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0],
      dtype=int64)

In [52]:
submission = pd.read_csv("gender_submission.csv")
submission['Survived'] = y_pred
submission.to_csv("gender_submission.csv", index=False)